version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: telegram-mcp
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: false
    files:
      - none*

changelog:
  use: github
  sort: asc
  groups:
    - title: Release Notes
      regexp: ".*"
  filters:
    exclude:
      - ".*"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256 