version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: telegram-mcp
    ldflags:
      - -s -w

archives:
  - format_overrides:
    - formats:  'zip'
      goos: windows

changelog:
  use: github
  sort: asc

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256 